# Generated by Django 6.0.1 on 2026-01-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_participants',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='event',
            name='pdf_resource',
            field=models.FileField(blank=True, null=True, upload_to='event_pdfs/'),
        ),
    ]
