# Generated by Django 6.0.1 on 2026-01-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_event_max_participants_event_pdf_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
