# Generated by Django 6.0.1 on 2026-01-11 08:02

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_participant_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=75, scale=None, size=[800, 600], upload_to='events/'),
        ),
    ]
