# Generated by Django 6.0.1 on 2026-01-11 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_participant_attended_participant_qr_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Intra IT Fest 2026'", max_length=200)),
                ('year', models.IntegerField(default=2026)),
                ('is_active', models.BooleanField(default=True)),
                ('brochure', models.FileField(blank=True, null=True, upload_to='fest_docs/')),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='is_fest_event',
            new_name='is_team_event',
        ),
        migrations.AddField(
            model_name='event',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='max_team_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='min_team_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='participant',
            name='current_round',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='participant',
            name='is_winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='team_members',
            field=models.TextField(blank=True, help_text='Comma separated names of members', null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='team_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='EventRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(default=1)),
                ('name', models.CharField(default='Preliminary Round', max_length=100)),
                ('selection_limit', models.IntegerField(default=10, help_text='How many teams/people qualify for the next round?')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='api.event')),
            ],
            options={
                'ordering': ['round_number'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='fest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.fest'),
        ),
        migrations.DeleteModel(
            name='Leaderboard',
        ),
    ]
