# Generated by Django 6.0.1 on 2026-01-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_fest_rename_is_fest_event_event_is_team_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='rank',
            field=models.IntegerField(blank=True, help_text='1 for 1st Prize, 2 for 2nd, etc.', null=True),
        ),
    ]
