# Generated by Django 6.0.1 on 2026-01-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_teammember_event_results_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='custom_fields',
            field=models.JSONField(blank=True, default=list, help_text="List of extra field labels e.g. ['GitHub Link', 'Dietary Pref']"),
        ),
        migrations.AddField(
            model_name='event',
            name='payment_qr',
            field=models.ImageField(blank=True, null=True, upload_to='payment_qrs/'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_fee',
            field=models.IntegerField(default=0, help_text='0 for free events'),
        ),
        migrations.AddField(
            model_name='participant',
            name='custom_responses',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='participant',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='participant',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventround',
            name='selection_limit',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='participant',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='team_members',
            field=models.TextField(blank=True, null=True),
        ),
    ]
